name: "test"
description: "test"
inputs:
   sim_path:
     required: false
     description: "Docker registry"
     
runs:
  using: "composite"
  steps:
    - name: Delete Old Tags
      shell: bash
      run: |
          version=$(git rev-parse --short HEAD)
          echo $version
          ls README.md
