on: 
  push:
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - run: mkdir sgkbdir
      - id: foo
        uses: kaibo11/testCreateAction@latest
        with:
          who-to-greet: 'Mona the  Octocat'

      - uses: kaibo11/upload-artifact@ef09cdac3e2d3e60d8ccadda691f4f1cec5035cb
        with:
          name: my-artifact
          path: README.md
          
      - name: Hello world action step
        id: hello
        uses: kaibo11/test-javascript-action@main
        with:
          who-to-greet: 'Mona the  Octocat'

      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
        
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
        
      - uses: webiny/action-post-run@3.1.0
        id: post-run-command
        with:
          run: echo "this thing works!"

          

